<template>
  <section class="admin-orders page-shell">
    <div class="admin-header"><div><h1 class="page-title">订单管理</h1><p class="page-subtitle">发货处理与取消申请审核</p></div></div>
    <el-tabs v-model="activeTab" @tab-click="changeTab">
      <el-tab-pane label="发货管理" name="shipping">
        <div class="toolbar"><el-select v-model="status" clearable placeholder="全部状态" @change="fetchOrders"><el-option label="待发货" :value="1"/><el-option label="已发货" :value="2"/><el-option label="已完成" :value="3"/></el-select></div>
        <el-table v-loading="loading" :data="orders" class="admin-table"><el-table-column prop="orderSn" label="订单号" min-width="190"/><el-table-column prop="nickName" label="用户" width="120"/><el-table-column prop="costPoints" label="积分" width="100"/><el-table-column prop="status" label="状态" width="100"/><el-table-column prop="createTime" label="下单时间" min-width="170"/><el-table-column label="操作" width="120"><template slot-scope="scope"><el-button v-if="canShip(scope.row)" type="primary" size="mini" @click="openShip(scope.row)">发货</el-button><el-button v-else-if="scope.row.statusCode === 2" size="mini" @click="openTrack(scope.row)">更新物流</el-button></template></el-table-column></el-table>
      </el-tab-pane>
      <el-tab-pane label="取消审核" name="cancellations">
        <div class="toolbar"><el-select v-model="cancelStatus" clearable placeholder="全部申请状态" @change="fetchCancelRequests"><el-option label="待审核" :value="0"/><el-option label="已通过" :value="1"/><el-option label="已拒绝" :value="2"/></el-select></div>
        <el-table v-loading="cancelLoading" :data="cancelRequests" class="admin-table"><el-table-column prop="orderSn" label="订单号" min-width="180"/><el-table-column prop="nickName" label="用户" width="120"/><el-table-column prop="reason" label="取消原因" min-width="200" show-overflow-tooltip/><el-table-column prop="costPoints" label="返还积分" width="100"/><el-table-column prop="statusText" label="状态" width="100"/><el-table-column prop="createTime" label="申请时间" min-width="170"/><el-table-column label="审核" width="170"><template slot-scope="scope"><template v-if="scope.row.statusText === '待审核'"><el-button type="success" size="mini" @click="audit(scope.row, true)">通过</el-button><el-button type="danger" size="mini" @click="audit(scope.row, false)">拒绝</el-button></template><span v-else>{{ scope.row.auditRemark || '-' }}</span></template></el-table-column></el-table>
      </el-tab-pane>
    </el-tabs>
    <el-dialog :title="dialogTitle" :visible.sync="dialogVisible" width="440px"><el-form :model="shipForm" label-width="88px"><template v-if="dialogMode === 'ship'"><el-form-item label="物流公司"><el-input v-model.trim="shipForm.shippingCompany"/></el-form-item><el-form-item label="物流单号"><el-input v-model.trim="shipForm.trackingNo"/></el-form-item></template><el-form-item label="物流状态"><el-input v-model.trim="shipForm.trackStatus" placeholder="例如：已揽收、运输中、已签收"/></el-form-item><el-form-item label="物流说明"><el-input v-model.trim="shipForm.description" type="textarea"/></el-form-item><el-form-item label="地点"><el-input v-model.trim="shipForm.location"/></el-form-item></el-form><div slot="footer"><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="submit">保存</el-button></div></el-dialog>
  </section>
</template>
<script>
import api from '@/utils/api'
const emptyForm = () => ({ shippingCompany: '', trackingNo: '', trackStatus: '已揽收', description: '', location: '' })
export default { data() { return { activeTab: 'shipping', orders: [], cancelRequests: [], loading: false, cancelLoading: false, saving: false, status: 1, cancelStatus: 0, dialogVisible: false, dialogMode: 'ship', currentOrder: null, shipForm: emptyForm() } }, computed: { dialogTitle() { return this.dialogMode === 'ship' ? '订单发货' : '更新物流' } }, created() { this.fetchOrders() }, methods: { canShip(order) { return order.statusCode === 1 && order.status === '待发货' }, changeTab() { if (this.activeTab === 'cancellations') this.fetchCancelRequests() }, async fetchOrders() { this.loading = true; try { const res = await api.get('/admin/orders', { params: { status: this.status } }); this.orders = res.data } finally { this.loading = false } }, async fetchCancelRequests() { this.cancelLoading = true; try { const res = await api.get('/admin/cancel-requests', { params: { status: this.cancelStatus } }); this.cancelRequests = res.data } finally { this.cancelLoading = false } }, openShip(order) { if (!this.canShip(order)) { this.$message.warning('订单已不是待发货状态，请刷新后重试'); return } this.currentOrder = order; this.shipForm = emptyForm(); this.dialogMode = 'ship'; this.dialogVisible = true }, openTrack(order) { this.currentOrder = order; this.shipForm = { ...emptyForm(), trackStatus: '运输中' }; this.dialogMode = 'track'; this.dialogVisible = true }, async submit() { this.saving = true; try { const isShipping = this.dialogMode === 'ship'; const orderId = this.currentOrder.id; if (isShipping) await api.post(`/admin/orders/${orderId}/ship`, { shippingCompany: this.shipForm.shippingCompany, trackingNo: this.shipForm.trackingNo, description: this.shipForm.description || '快件已揽收' }); else await api.post(`/admin/orders/${orderId}/logistics-events`, { trackStatus: this.shipForm.trackStatus, description: this.shipForm.description, location: this.shipForm.location }); if (isShipping) this.orders = this.orders.filter(order => order.id !== orderId); this.$message.success('操作成功'); this.dialogVisible = false; await this.fetchOrders() } finally { this.saving = false } }, async audit(row, approved) { try { const result = await this.$prompt(approved ? '填写通过备注（可选）' : '请输入拒绝原因', approved ? '通过取消申请' : '拒绝取消申请', { inputPattern: approved ? undefined : /\S+/, inputErrorMessage: '拒绝原因不能为空' }); await api.post(`/admin/cancel-requests/${row.id}/${approved ? 'approve' : 'reject'}`, { remark: result.value || '' }); this.$message.success(approved ? '已通过并返还积分' : '已拒绝申请'); await this.fetchCancelRequests() } catch (error) { if (error !== 'cancel') this.$message.error(error.response?.data?.msg || '审核失败') } } } }
</script>
<style scoped>
.admin-header{margin-bottom:18px}.toolbar{display:flex;justify-content:flex-end;margin-bottom:14px}.admin-table{border-radius:12px;background:#fff}.admin-table ::v-deep .el-table__header th{background:#f7f9fc;color:var(--pm-text-secondary)}@media(max-width:768px){.toolbar{justify-content:flex-start}.admin-table{font-size:12px}}
</style>
